hyplus:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost   # 默认
    port: 3306        # 默认
    database: hyplus-foodie
    username: %YOUR-USERNAME%
    password: %YOUR-PASSWORD%
  alioss:
    endpoint: %YOUR-ENDPOINT%
    access-key-id: %YOUR-ACCESS-KEY-ID%
    access-key-secret: %YOUR-ACCESS-KEY-SECRET%
    bucket-name: %YOUR-BUCKET-NAME%
  redis:
    host: localhost # 默认
    port: 6379      # 默认
    password: %YOUR-PASSWORD%   # 无密码则无视该行
    database: 0     # 默认
  wechat:
    appid: %YOUR-APPID%
    secret: %YOUR-SECRET%
    mchid: %YOUR-MCHID%
    mch-serial-no: %YOUR-MCH-SERIAL-NO%
    private-key-file-path: %YOUR-PRIVATE-KEY-FILE-PATH%
    api-v3-key: %YOUR-API-V3-KEY%
    we-chat-pay-cert-file-path: %YOUR-WE-CHAT-PAY-CERT-FILE-PATH%
    notify-url: %YOUR-NOTIFY-URL%
    refund-notify-url: %YOUR-REFUND-NOTIFY-URL%
  shop:
    address: 浙江省杭州市拱墅区Hyperplasma广场三号楼12层
  baidu:
    ak: %YOUR-BAIDU-ACCESS-KEY%